# Generated by Django 2.2.3 on 2019-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='entrance_fee',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, default='제주', max_length=200),
        ),
    ]
