# Generated by Django 2.2.3 on 2019-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190718_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
