# Generated by Django 2.2.3 on 2019-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='name',
            field=models.CharField(db_index=True, default='공지사항', max_length=200),
        ),
    ]
