# Generated by Django 2.2.5 on 2019-09-17 02:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='images/no_image.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
