# Generated by Django 2.2.5 on 2019-09-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
